// ── boneyard-js bone registry ────────────────────────────────
// This file is auto-generated by `npx boneyard-js build`.
// Run that command to capture pixel-perfect skeleton bones from
// the live DOM — it scans every <Skeleton name="..."> in the app
// and writes JSON files into this folder, then imports them here.
//
// Until you run the build at least once, this stub is a no-op:
// <Skeleton> falls back to its `fallback` prop or shows nothing.
// ─────────────────────────────────────────────────────────────
export {};
